In [1]:
import numpy as np

In [2]:
test_scores = [ 70,65,95,88 ]
type(test_scores)

list

In [3]:
scores = np.array(test_scores)
type(scores)

numpy.ndarray

In [4]:
print(np.sum(scores))
print(np.mean(scores))

print(scores.mean())
print(scores.sum())

318
79.5
79.5
318


In [12]:
#  Using Income
income = np.array([75000, 55000, 88000, 125000, 64000, 97000])


In [13]:

print(income.sum()  , 
income.mean())


504000 84000.0


In [14]:
income = np.append(income, 12000000)
income.mean()



1786285.7142857143

In [15]:
np.median(income)


88000.0

In [17]:
income.std()

4169786.007331644

In [20]:
scores.min()

65

In [22]:
scores.max()

95

In [23]:
#  WORK WITH MATRICS
np.random.seed(seed= 60)
random_square = np.random.rand(5,5)
random_square

array([[0.30087333, 0.18694582, 0.32318268, 0.66574957, 0.5669708 ],
       [0.39825396, 0.37941492, 0.01058154, 0.1703656 , 0.12339337],
       [0.69240128, 0.87444156, 0.3373969 , 0.99245923, 0.13154007],
       [0.50032984, 0.28662051, 0.22058485, 0.50208555, 0.63606254],
       [0.63567694, 0.08043309, 0.58143375, 0.83919086, 0.29301825]])

In [28]:
random_square[:]

array([[0.30087333, 0.18694582, 0.32318268, 0.66574957, 0.5669708 ],
       [0.39825396, 0.37941492, 0.01058154, 0.1703656 , 0.12339337],
       [0.69240128, 0.87444156, 0.3373969 , 0.99245923, 0.13154007],
       [0.50032984, 0.28662051, 0.22058485, 0.50208555, 0.63606254],
       [0.63567694, 0.08043309, 0.58143375, 0.83919086, 0.29301825]])

In [29]:
# First col
random_square[:,0]

array([0.30087333, 0.39825396, 0.69240128, 0.50032984, 0.63567694])

In [30]:
#  First entry
random_square[0,0]

0.30087333004661876

In [31]:
%%time
np.random.seed(seed=60)
big_matrix = np.random.rand(100000,100)

Wall time: 97.8 ms


In [44]:
%%time
big_matrix = np.random.rand(100000, 100)
big_matrix.mean()

Wall time: 246 ms


0.5001944568716994